services:
  - name: ml-api
    type: web
    env: python
    rootDir: ml-model # ✅ Only deploy the ml-model folder
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: PORT
        value: 10000
